<?php

namespace DoctrineProxies\__CG__;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EnderecoEntity extends \EnderecoEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'cep', 'endereco', 'numero', 'complemento', 'bairro', 'cidade', 'estado', 'referencias', 'tiposEstado', 'listSeparator'];
        }

        return ['__isInitialized__', 'id', 'cep', 'endereco', 'numero', 'complemento', 'bairro', 'cidade', 'estado', 'referencias', 'tiposEstado', 'listSeparator'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EnderecoEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getGoogleString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogleString', []);

        return parent::getGoogleString();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnderecoArgs($args)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnderecoArgs', [$args]);

        return parent::setEnderecoArgs($args);
    }

    /**
     * {@inheritDoc}
     */
    public function __call($name, $arguments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', [$name, $arguments]);

        return parent::__call($name, $arguments);
    }

    /**
     * {@inheritDoc}
     */
    public function defineCallParam($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'defineCallParam', [$name]);

        return parent::defineCallParam($name);
    }

    /**
     * {@inheritDoc}
     */
    public function udata($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'udata', [$data]);

        return parent::udata($data);
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', [$data]);

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function checkAndConvertDataToDate($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkAndConvertDataToDate', [$data]);

        return parent::checkAndConvertDataToDate($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData($campo, $format)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', [$campo, $format]);

        return parent::getData($campo, $format);
    }

    /**
     * {@inheritDoc}
     */
    public function ptbrToFloat($valor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'ptbrToFloat', [$valor]);

        return parent::ptbrToFloat($valor);
    }

    /**
     * {@inheritDoc}
     */
    public function getObject($param, $class)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObject', [$param, $class]);

        return parent::getObject($param, $class);
    }

    /**
     * {@inheritDoc}
     */
    public function validaCnpj($cnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validaCnpj', [$cnpj]);

        return parent::validaCnpj($cnpj);
    }

}
