<?php
if ($v->getNoVisibleElements() === false)	{ ?>

			<!-- left menu starts -->
			<div class="span2 main-menu-span no-print">
				<div class="well nav-collapse sidebar-nav">
					<div id="menu-principal">
						<ul class="nav nav-tabs nav-stacked main-menu">
							<li class="nav-header hidden-tablet"><?php echo $assinanteNome; ?></li>
							<li><a href="<?php echo $indexPainel; ?>"><i class="fa fa-home black"></i><span class="hidden-tablet"> Painel</span></a></li>
							<li><a href="<?php echo $index; ?>pedidos/cliente"><i class="black fa fa-plus"></i><span class="hidden-tablet"> Nova locação</span></a></li>
							<li><a href="<?php echo $index; ?>clientes"><i class="black fa fa-users"></i><span class="hidden-tablet"> Clientes</span></a></li>
							<li><a href="<?php echo $index; ?>pedidos/novos/locacoes"><i class="black fa fa-retweet"></i><span class="hidden-tablet"> Locações</span></a></li>
							<li><a href="<?php echo $index; ?>pedidos/novos/entregas"><i class="black fa fa-arrow-right"></i><span class="hidden-tablet"> Vendas</span></a></li>
							<li><a href="<?php echo $index; ?>financeiro/geral/<?php echo date('Ym01'); ?>/<?php echo date('Ymt'); ?>/emissao"><i class="black fa fa-briefcase"></i><span class="hidden-tablet"> Financeiro</span></a></li>
							<li><a href="<?php echo $index; ?>cacambas"><i class="black fa fa-inbox"></i><span class="hidden-tablet"> Caçambas</span></a></li>
							<li><a href="<?php echo $index; ?>motoristas/atividade/consolidado/<?php echo date('Ym01'); ?>/<?php echo date('Ymt'); ?>"><i class="black fa fa-exchange"></i><span class="hidden-tablet"> Atividade dos motoristas</span></a></li>
						</ul>
					</div>
					<div id="menu-cadastros">
						<ul class="nav nav-tabs nav-stacked main-menu">
							<li class="nav-header hidden-tablet">Cadastros</li>
							<li><a class="" href="<?php echo $index; ?>formas-de-pagamento"><i class="black fa fa-credit-card"></i><span class="hidden-tablet"> Formas de pagamento</span></a></li>
	 						<li><a class="" href="<?php echo $index; ?>caixas"><i class="black fa fa-usd"></i><span class="hidden-tablet"> Caixas</span></a></li>
							<li><a class="" href="<?php echo $index; ?>tipos-de-cacamba"><i class="black fa fa-cog"></i><span class="hidden-tablet"> Tipos de Cacamba</span></a></li>
							<li><a class="" href="<?php echo $index; ?>produtos"><i class="black fa fa-shopping-cart"></i><span class="hidden-tablet"> Produtos</span></a></li>
							<li><a class="" href="<?php echo $index; ?>motoristas"><i class="black fa fa-truck"></i><span class="hidden-tablet"> Motoristas</span></a></li>
	<!-- 						<li><a class="" href="<?php echo $index; ?>assinantes"><i class="black fa fa-users"></i><span class="hidden-tablet"> Assinantes</span></a></li> -->
	<!-- 						<li><a class="Cupcake-nav" href="#"><i class="black fa fa-eye-open"></i><span class="hidden-tablet"> Faturamento</span></a></li> -->
						</ul>
					</div>
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li class="nav-header hidden-tablet">Sistema</li>
						<li><a href="<?php echo $index ?>configuracoes" id="menu-config"><i class="black fa fa-cog"></i><span class="hidden-tablet"> Configurações</span></a></li>
						<li><a href="<?php echo $index ?>sair"><i class="black fa fa-power-off"></i><span class="hidden-tablet"> Sair</span></a></li>
					</ul>
					<!-- <label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><input id="is-ajax" type="checkbox"> Ajax on menu</label> -->
				</div><!--/.well -->
			</div><!--/span-->
			<!-- left menu ends -->

			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>

<?php } ?>