<?php
/**
 * (c) CupcakePHP: The Rapid and Tasty Development Framework.
 *
 * PHP version 5.5.12
 *
 * @author  Ge Bender <gesianbender@gmail.com>
 * @license http://www.opensource.org/licenses/mit-license.php MIT License
 * @version GIT: <git_id>
 * @link    http://cupcake.simplesys.com.br
 */
?>
<div class="row">
    <div class="col-sm-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo $indexPainel; ?>"><i class="fa fa-home"></i> Painel</a></li>
            <li><a href="<?php echo $indexController; ?>"><i class="<?php echo $icon; ?>"></i> <?php echo $dados->getPlural(); ?></a></li>
            <li class="active"><i class="fa fa-plus"></i> Inserir nov<?php echo $dados->getGenero(); ?> <?php echo $dados->getSingular(); ?></li>
        </ul>

		<div class="panel panel-btns">
	        <a href="<?php echo $indexController; ?>" class="btn btn-small btn-success btn-shadow">
	            <span class="white fa fa-list"></span> Listar
	        </a>
        </div>

        <section class="panel">
            <header class="panel-heading">
                <i class="<?php echo $icon; ?>"></i> Nov<?php echo $dados->getGenero(); ?> <?php echo $dados->getSingular(); ?>
            </header>
            <div class="row panel-body">
                <div class="col-sm-12">
                    <form class="form-horizontal tasi-form ajax-form" id="<?php echo $titulo; ?>-form" method="post" action="<?php echo $indexController; ?>salvar">
                        <fieldset>
                            <input type="hidden" name="<?php echo $titulo; ?>[id]" value="<?php echo $dados->getId(); ?>">
                            <input type="hidden" name="saida" value="<?php echo $saida; ?>">
                            <input type="hidden" name="flashMsg" value="<?php echo $msgFlash; ?>">

                            <?php for ($i=0; isset($campos[$i]) === true; $i++) { ?>
                            <div class="form-group">
                                <label class="col-lg-2 col-sm-2 control-label" for="form-field-<?php echo $i; ?> ">
                                    <strong><?php echo $dados->getLabel($campos[$i]); ?>:</strong>
                                </label>
                                <div class="col-sm-10">
                                    <?php echo $form->field($campos[$i], $dados->$campos[$i], array('class' => 'form-control', 'id' => 'form-field'.$i)); ?>
                                </div>
                            </div>
                            <?php } ?>
                            <div class="form-group">
                                <div class="col-lg-2 col-sm-2 control-label"></div>

                                <div class="col-lg-10" style="text-align:right">
                                    <button type="submit" class="btn btn-warning btn-shadow" style="width:150px">
                                        <i class="white fa fa-check"></i> Salvar</button>
                                    <button type="reset" class="btn btn-default btn-shadow darkgray">
                                        <i class="white fa fa-eraser darkgray"></i> Cancelar
                                    </button>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </section>
    </div>
</div>
