<?php
/**
 * (c) CupcakePHP: The Rapid and Tasty Development Framework.
 *
 * PHP version 5.5.12
 *
 * @author  Ge Bender <gesianbender@gmail.com>
 * @license http://www.opensource.org/licenses/mit-license.php MIT License
 * @version GIT: <git_id>
 * @link    http://cupcake.simplesys.com.br
 */
?>
<div class="row">
    <div class="col-sm-12">
        <ul class="breadcrumb">
            <li><i class="fa fa-home"></i> <a href="<?php echo $indexPainel; ?>">Painel</a></li>
            <li class="active"><i class="<?php echo $icon; ?>"></i> <?php echo $dados->getPlural(); ?></li>
        </ul>

        <div style="margin-bottom: 14px;">
            <a href="<?php echo $indexController; ?>novo" class="btn btn-small btn-success btn-shadow">
                <span class="white fa fa-plus"></span> Inserir novo
            </a>
        </div>

        <section class="panel">
            <header class="panel-heading">
                <strong><i class="<?php echo $icon; ?>"></i> <?php echo $dados->getPlural(); ?></strong>
                <span class="right" style="margin-top: -5px;"><?php echo $headerLista; ?></span>
            </header>

            <div class="panel-body">
                <?php if (count($results) > 0) { ?>
                    <table class="table table-bordered table-striped table-condensed">
                        <thead>
                            <tr>
                            <?php foreach ($colunas as $coluna) { ?>
                                <th><?php echo $lista->getTituloColuna($coluna); ?>
                                    <a href="<?php echo $lista->getLinkOrder($coluna); ?>">
                                        <i class="<?php echo $lista->getIconOrder($coluna); ?> right"></i>
                                    </a>
                                </th>
                            <?php } ?>
                                <th style="max-width:90px">Ações</th>
                            </tr>
                        </thead>
                    <tbody>
                    <?php foreach ($results as $result) { ?>
                        <tr>
                        <?php foreach ($colunas as $coluna) { ?>
                            <td><?php echo $pages->viewLista($result, $coluna); ?></td>
                        <?php } ?>
                            <td style="max-width:90px">
                            <div class="btn-group">
		            			<button data-toggle="dropdown" class="btn btn-primary dropdown-toggle btn-sm btn-shadow" type="button" aria-expanded="false">Opções <span class="caret"></span></button>
		            			<ul role="menu" class="dropdown-menu pull-right">
		                            <li><a href="<?php echo $indexController; ?>ver/<?php echo $result->getId(); ?>"><i class="fa fa-plus-circle"></i> Detalhes</a></li>
		                            <li><a href="<?php echo $indexController; ?>editar/<?php echo $result->getId(); ?>"><i class="fa fa-pencil-square-o"></i> Editar</a></li>
		                           <li class="divider"></li>
		                            <li><a class="btn-delete" href="#" data-rel="<?php echo $result->getId(); ?>"><i class="fa fa-trash-o red"></i> Deletar</a></li>
		                        </ul>
		                     </div>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <?php } else { ?>
                <div class="alert alert-blck alert-warning center" style="margin-top: 15px">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <i class="fa fa-4x fa-frown-o"></i><br/>
                    <strong>Ops!</strong> Nenhum resultado para esta busca.
                </div>
                <?php } ?>

                <?php echo $pagination; ?>
            </div>
        </section>
    </div><!--/span-->
</div>

<script>
    $(document).ready(function() {
        $('.btn-delete').click(function() {
            $('#modal-footer-default').hide();
            CupcakeAlert(
                '<a class="btn btn-danger ajax-link" href="<?php echo $indexController; ?>deletar/'+$(this).attr('data-rel')+'/?<?php echo (isset($requestUri[1]) === true) ? urlencode(($requestUri[1])) : ''; ?>"><i class="fa fa-trash-o white"></i> Confirma</a>',
                'Confirma a remoção deste registro?'
            );
            CupcakeReady();
        });
    });
</script>
