<?php
/**
 * (c) CupcakePHP: The Rapid and Tasty Development Framework.
 *
 * PHP version 5.5.12
 *
 * @author  Ge Bender <gesianbender@gmail.com>
 * @license http://www.opensource.org/licenses/mit-license.php MIT License
 * @version GIT: <git_id>
 * @link    http://cupcake.simplesys.com.br
 */
?>
<div class="row">
    <div class="col-sm-12">
        <ul class="breadcrumb">
            <li><i class="fa fa-home"></i> <a href="<?php echo $indexPainel; ?>">Painel</a></li>
            <li class="active"><i class="<?php echo $icon; ?>"></i> <?php echo $dados->getPlural(); ?></li>
        </ul>

		<div class="panel panel-btns">
	        <a href="<?php echo $indexController; ?>novo" class="btn btn-sm btn-success btn-shadow">
	            <span class="white fa fa-plus-circle"></span> Inserir novo
	        </a>
	    </div>

        <section class="panel">
            <header class="panel-heading tab-bg-dark-navy-blue">
                <span class="hidden-sm wht-color"><i class="<?php echo $icon; ?>"></i> <?php echo $dados->getPlural(); ?></span>
                <span class="right"><?php echo $headerLista; ?></span>
            </header>

            <div class="panel-body" style="padding-bottom: 100px">
                <?php if (count($results) > 0) { ?>
                    <table class="table table-striped">
                        <thead>
                            <tr>
                            <?php foreach ($colunas as $coluna) { ?>
                                <th>
                                    <a href="<?php echo $lista->getLinkOrder($coluna); ?>">
                                        <i class="<?php echo $lista->getIconOrder($coluna); ?>" style="margin-right: 3px;"></i>
                                        <?php echo $lista->getTituloColuna($coluna); ?>
                                    </a>
                                </th>
                            <?php } ?>
                                <th style="max-width:90px">Ações</th>
                            </tr>
                        </thead>
                    <tbody>
                    <?php foreach ($results as $result) { ?>
                        <tr>
                        <?php foreach ($colunas as $coluna) { ?>
                            <td><?php echo $pages->viewLista($result, $coluna); ?></td>
                        <?php } ?>
                            <td style="max-width:90px">
                                <div class="btn-group">
                                    <a href="<?php echo $indexController; ?>editar/<?php echo $result->getId(); ?>" class="btn btn-sm btn-warning modal-link" style="border-color:#FFF;">
                                        <i class="fa fa-pencil-square"></i> Editar</a>
                                    <button data-toggle="dropdown" class="btn btn-sm btn-warning dropdown-toggle" type="button" aria-expanded="false" style="border-color:#FFF;">
                                        <span class="caret"></span>
                                    </button>
                                    <ul role="menu" class="dropdown-menu">
                                        <li><a href="<?php echo $indexController; ?>ver/<?php echo $result->getId(); ?>"><i style="min-width: 20px" class="fa fa-search-plus"></i> Detalhes</a></li>
                                        <li class="divider"></li>
                                        <li><a class="link-delete" href="#" data-rel="<?php echo $result->getId(); ?>"><i style="min-width: 20px" class="fa fa-trash"></i> Deletar</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
                <?php } else { ?>
                <div class="alert alert-blck alert-warning center" style="margin-top: 15px">
                    <i class="fa fa-4x fa-frown-o"></i><br/>
                    <strong>Ops!</strong> Nenhum resultado para esta busca.
                </div>
                <?php } ?>

                <?php echo $pagination; ?>
            </div>
        </section>
    </div><!--/span-->
</div>

<script>
    $(document).ready(function() {
        $('.link-delete').click(function() {
            $('#modal-footer-default').hide();
            CupcakeAlert('<a class="btn btn-danger ajax-link" href="<?php echo $indexController; ?>deletar/'+$(this).attr('data-rel')+'/?<?php echo (isset($requestUri[1]) === true) ? urlencode(($requestUri[1])) : ''; ?>"><i class="fa fa-trash-o white"></i> Confirma</a>',
                    '',
                    'Confirma a remoção deste registro?'

            );
            CupcakeReady();
        });
    });
</script>
