<?php
/**
 * (c) CupcakePHP: The Rapid and Tasty Development Framework.
 *
 * PHP version 5.5.12
 *
 * @author  Ge Bender <gesianbender@gmail.com>
 * @license http://www.opensource.org/licenses/mit-license.php MIT License
 * @version GIT: <git_id>
 * @link    http://cupcake.simplesys.com.br
 */
?>
<ul class="breadcrumb">
    <li><a href="<?php echo $indexPainel; ?>">Painel</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $indexController; ?>"><?php echo $titulo; ?></a> <span class="divider">/</span></li>
    <li><a href="#"><?php echo $migalha; ?></a></li>
</ul>

<a href="<?php echo $indexController; ?>" class="btn btn-small btn-success"><span class="white fa fa-undo"></span> Listar <?php echo $titulo; ?></a>

<div class="row-fluid">
    <div class="box span12">
        <div class="box-header well" data-original-title=""><h2><i class="<?php echo $icon; ?>"></i> <?php echo $acao; ?> de <?php echo $titulo; ?></h2></div>
        <div class="box-content">
            <div class="row-fluid">
                <div class="span6">
                    <table style="" class="table table-view">
                        <tbody>
                        <?php for ($i=0; $i<ceil((count($campos) / 2)); $i++) { ?>
                            <tr><td><?php echo ucfirst($campos[$i]); ?>: <b> <?php echo $dados->$campos[$i]; ?></b></td></tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>

                <div class="span6">
                    <table style="" class="table table-view">
                        <tbody>
                        <?php for ($i=$i; isset($campos[$i]) === true; $i++) { ?>
                            <tr><td><?php echo ucfirst($campos[$i]); ?>: <b> <?php echo $dados->$campos[$i]; ?></b></td></tr>
                        <?php } ?>
                        </tbody>
                    </table>
                    <a href="<?php echo $indexController; ?>editar/<?php echo $dados->getId(); ?>" class="right btn btn-warning"><i class="white fa fa-pencil-square-o"></i> Editar</a>
                </div>
            </div>
        </div>
    </div>
</div>






