<?php
/**
 * (c) CupcakePHP: The Rapid and Tasty Development Framework.
 *
 * PHP version 5.5.12
 *
 * @author  Ge Bender <gesianbender@gmail.com>
 * @license http://www.opensource.org/licenses/mit-license.php MIT License
 * @version GIT: <git_id>
 * @link    http://cupcake.simplesys.com.br
 */
?>
<div class="row">
    <div class="col-sm-12">
        <ul class="breadcrumb">
            <li><a href="<?php echo $indexPainel; ?>">Painel</a></li>
            <li><a href="<?php echo $indexController; ?>"><?php echo $titulo; ?></a> </li>
            <li><a href="#"><?php echo $migalha; ?></a></li>
        </ul>

        <div class="panel panel-btns">
	        <a href="<?php echo $indexController; ?>" class="btn btn-sm btn-primary btn-shadow">
	            <span class="white fa fa-list"></span> Listar
	        </a>
	        <a href="<?php echo $indexController; ?>editar/<?php echo $dados->getId(); ?>" class="btn btn-warning btn-sm btn-shadow">
	            <i class="white fa fa-pencil-square-o"></i> Editar
	        </a>
        </div>

        <section class="panel">
            <header class="panel-heading">
                <i class="<?php echo $icon; ?>"></i> <?php echo $acao; ?> de <strong><?php echo $titulo; ?> <?php echo $migalha ?></strong>
            </header>
            <div class="row panel-body">
                <div class="col-sm-12">
                    <table class="table table-bordered table-striped table-condensed">
                        <tbody>
                        <?php for ($i=0; isset($campos[$i]) === true; $i++) { ?>
                            <tr>
                                <td><strong><?php echo $dados->getLabel($campos[$i]); ?>: </strong></td>
                                <td><?php echo $pages->showData($dados, $campos[$i]); ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </section>
    </div><!--/span-->
</div>
