<?php
/**
 * Simplifica: Afinal, programar pode ser simples
 *
 * PHP version 5.4.12
 *
 * @category  Templates
 * @package   Charisma
 * @author    Ge Bender <gesianbender@gmail.com>
 * @copyright 2014 - Projeto Simplifica PHP
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 * @version   GIT: <git_id>
 * @link      http://php.simplifica.com.br
 */
?>
A fazer, o famoso: toDo
