<?php if ($v->hasNoVisibleElements() === false)    { ?>

<!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              &copy; Copyright <?php echo date('Y'); ?>
              <a href="#" class="go-top">
                  <i class="icon-angle-up"></i>
              </a>
          </div>
      </footer>
      <!--footer end-->
<?php } ?>
</section>

<div class="loading-modal"><a class="modal-spin fa white fa-spinner fa-spin fa-4x fa-fw"></a></div>
<div class="history-main-content"></div>

<?php if($alert !== false) { ?>
    <script>
    $(document).ready(function() {
    	CupcakeAlert('<?php echo $alert; ?>');
    });
    </script>
    <?php } ?>

    <?php if ($topFull !== false) { ?>
        <button class="noty" style="display: none;" id="top-full-call" data-noty-options='{<?php echo $topFull; ?>}'></button>
        <script>
        $(document).ready(function() {
            $('#top-full-call').click();
        });
        </script>
    <?php } ?>

    <?php if ($modal !== false) { ?>
        <div class="modal hide fade" id="cupcakeModal">
            <?php echo $modal; ?>
        </div>

        <script>
        $(document).ready(function() {
        	$('#cupcakeModal').modal('show');
        });
        </script>
    <?php } ?>

    <!-- js placed at the end of the document so the pages load faster -->
    <script type="text/javascript"  src="<?php echo $cupcakeAsset; ?>js/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" defer src="<?php echo $cupcakeAsset; ?>jquery-ui/jquery-ui.min.js"></script>
    <script type="text/javascript" src="<?php echo $cupcakeAsset; ?>js/modernizr-custom.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="<?php echo $v->getLayoutAsset(); ?>js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/jquery.scrollTo.min.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/respond.min.js" ></script>

    <!--common script for all pages-->
    <script src="<?php echo $v->getLayoutAsset(); ?>js/common-scripts.js"></script>

    <script type="text/javascript" src="<?php echo $v->getCupcakeAsset(); ?>js/simplesys.js"></script>

    </body>
</html>
