<!-- Modal -->
                              <div class="modal fade" id="alertDefault" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                  <div class="modal-dialog">
                                      <div class="modal-content">
                                          <div class="modal-header">
                                              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                              <h4 class="modal-title">Modal Tittle</h4>
                                          </div>
                                          <div class="modal-body">

                                              Body goes here...

                                          </div>
                                          <div class="modal-footer">
                                              <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
                                              <button class="btn btn-success" type="button">Save changes</button>
                                          </div>
                                      </div>
                                  </div>
                              </div>

<?php if ($v->hasNoVisibleElements() === false)    { ?>


<!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              &copy; Copyright <?php echo date('Y'); ?>
              <a href="#" class="go-top">
                  <i class="fa fa-angle-up"></i>
              </a>
          </div>
      </footer>
      <!--footer end-->
<?php } ?>
</section>

<div class="loading-modal"><a class="modal-spin fa white fa-spinner fa-spin fa-4x fa-fw"></a></div>
<div class="history-main-content"></div>
<div class="dark-screen no-print"></div>

<?php if($alert !== false) { ?>
    <script>
    $(document).ready(function() {
    	CupcakeAlert('<?php echo $alert; ?>');
    });
    </script>
    <?php } ?>

    <?php if ($topFull !== false) { ?>
        <button class="noty" style="display: none;" id="top-full-call" data-noty-options='{<?php echo $topFull; ?>}'></button>
        <script>
        $(document).ready(function() {
            $('#top-full-call').click();
        });
        </script>
    <?php } ?>

    <?php if ($modal !== false) { ?>
        <div class="modal fade" id="cupcakeModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <?php echo $modal; ?>
        </div>

        <script>
        $(document).ready(function() {
        	$('#cupcakeModal').modal('show');
        });
        </script>
    <?php } ?>

    <!-- js placed at the end of the document so the pages load faster -->
    <script type="text/javascript"  src="<?php echo $cupcakeAsset; ?>js/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" defer src="<?php echo $cupcakeAsset; ?>jquery-ui/jquery-ui.min.js"></script>
    <script type="text/javascript" src="<?php echo $layoutAsset; ?>js/jquery-ui-1.9.2.custom.min.js"></script>

    <script type="text/javascript" src="<?php echo $cupcakeAsset; ?>js/modernizr-custom.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="<?php echo $v->getLayoutAsset(); ?>js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/jquery.scrollTo.min.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>assets/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/owl.carousel.js" ></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/jquery.customSelect.min.js" ></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/respond.min.js" ></script>

    <script class="include" type="text/javascript" src="<?php echo $v->getLayoutAsset(); ?>js/jquery.dcjqaccordion.2.7.js"></script>
    <!--common script for all pages-->
    <script src="<?php echo $v->getLayoutAsset(); ?>js/common-scripts.js"></script>
    <!--script for this page-->
    <script src="<?php echo $v->getLayoutAsset(); ?>js/sparkline-chart.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/easy-pie-chart.js"></script>
    <script src="<?php echo $v->getLayoutAsset(); ?>js/count.js"></script>
    <script src="<?php echo $cupcakeAsset; ?>js/cupcake.js"></script>

<?php echo implode("\n", $extraFooter); ?>
  <script>

      //owl carousel

      $(document).ready(function() {
          $("#owl-demo").owlCarousel({
              navigation : true,
              slideSpeed : 300,
              paginationSpeed : 400,
              singleItem : true,
			  autoPlay:true

          });
      });

      //custom select box

      $(function(){
          $('select.styled').customSelect();
      });

  </script>

    </body>
</html>
