<ul class="nav nav-tabs pull-right" style="margin-top: -5px;margin-right: 5px;">
    <li style="color: #FFF;padding: 10px;">
        <b><?php echo $lista->getTotal(); ?></b> registros,
    </li>
    <li>

            <select id="select-limit" class="form-control" style="width: 100%;height: 32px;border-radius: 0;">
              <option <?php if ($lista->limit === '10') echo "selected"; ?> value="<?php echo $lista->getLinkLimit(5); ?>">5</option>
              <option <?php if ($lista->limit === '10') echo "selected"; ?> value="<?php echo $lista->getLinkLimit(10); ?>">10</option>
              <option <?php if ($lista->limit === '25') echo "selected"; ?> value="<?php echo $lista->getLinkLimit(25); ?>">25</option>
              <option <?php if ($lista->limit === '50') echo "selected"; ?> value="<?php echo $lista->getLinkLimit(50); ?>">50</option>
              <option <?php if ($lista->limit === '50') echo "selected"; ?> value="<?php echo $lista->getLinkLimit(100); ?>">100</option>
              <option <?php if ($lista->limit === (string) $lista->getTotal()) echo "selected"; ?> value="<?php echo $lista->getLinkLimit($lista->getTotal()); ?>">Todos</option>
            </select>

    </li>
    <li style="color: #FFF;padding: 10px;">
         por página
    </li>
</ul>