<!DOCTYPE HTML>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $title; ?></title>
    <meta name="description" content="Just a simple template, a simple framework and a simple business">

    <?php 
    echo implode("\n", array_unique($extraHeaderA)); ?>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $layoutAsset; ?>css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $layoutAsset; ?>css/bootstrap-reset.css" rel="stylesheet">
    <link href="<?php echo $layoutAsset; ?>assets/font-awesome/css/font-awesome.css" rel="stylesheet">

    <!--external css-->

    <!-- Custom styles for this template -->
    <link href="<?php echo $layoutAsset; ?>css/style.css" rel="stylesheet">
    <link href="<?php echo $layoutAsset; ?>css/style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->

    <?php 
    echo implode("\n", array_unique($extraHeaderB)); ?>

	<link href="<?php echo $cupcakeAsset; ?>css/cupcake.css" rel="stylesheet">
	<link href="<?php echo $appAsset; ?>css/style.css" rel="stylesheet">
	
    <link rel="shortcut icon" href="<?php echo (isset($favicon) === true) ? $appAsset.$favicon : $cupcakeAsset.'images/favicon.png'; ?>">
    <link rel="icon" href="<?php echo (isset($favicon) === true) ? $appAsset.$favicon : $cupcakeAsset.'images/favicon.png'; ?>" type="image/x-icon">
    <script type="text/javascript" src="<?php echo $v->getLayoutAsset(); ?>js/jquery.js"></script>
</head>

<body class="<?php echo (isset($classBody) === true) ? $classBody : ''; ?>">

    <div class="modal fade" id="alertDefault" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                     <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                     <h4 class="modal-title" id="default-modal-title">Atenção</h4>
                 </div>
                 <div class="modal-body" id="default-modal-body"></div>
                 <div class="modal-footer" id="modal-footer-default">
                     <button class="btn btn-info" data-dismiss="modal" id="btn-modal-default" type="button"> Ok</button>
                 </div>
             </div>
         </div>
     </div>
