<?php
if ($v->hasNoVisibleElements() === false)	{ ?>
<!--header start-->
      <header class="header white-bg">


          <div class="sidebar-toggle-box">
              <div data-original-title="Mover o menu" data-placement="right" class="icon-reorder tooltips"><i class="fa fa-bars"></i></div>
              <!-- <div data-original-title="Fechar / abrir nenu" data-placement="right" class="fa fa-reorder tooltips"></div> -->
          </div>
          <!--logo start-->
          <a href="<?php echo $url; ?>" class="logo" ><?php echo $nomeSistema; ?></a>
          <!--logo end-->
          <div class="nav notify-row" id="top_menu">
            <!--  notification start -->
            <ul class="nav top-menu">
              <!-- settings start -->
              <li class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                      <i class="fa fa-tasks"></i>
                      <span class="badge bg-success">6</span>
                  </a>
                  <ul class="dropdown-menu extended tasks-bar">
                      <div class="notify-arrow notify-arrow-green"></div>
                      <li>
                          <p class="green">Há 6 lotes em andamento</p>
                      </li>
                      <li>
                          <a href="#">
                              <div class="task-info">
                                  <div class="desc">Lote 12 - Fazenda Triunfo</div>
                                  <div class="percent">40%</div>
                              </div>
                              <div class="progress progress-striped">
                                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                      <span class="sr-only">40% Complete (success)</span>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <div class="task-info">
                                  <div class="desc">Lote 2 - Fazenda Esperança</div>
                                  <div class="percent">60%</div>
                              </div>
                              <div class="progress progress-striped">
                                  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                      <span class="sr-only">60% Complete (warning)</span>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <div class="task-info">
                                  <div class="desc">Lote 67 - Fazenda Buriti</div>
                                  <div class="percent">87%</div>
                              </div>
                              <div class="progress progress-striped">
                                  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 87%">
                                      <span class="sr-only">87% Complete</span>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <div class="task-info">
                                  <div class="desc">Lote 1 - Fazenda Ouro verde</div>
                                  <div class="percent">33%</div>
                              </div>
                              <div class="progress progress-striped">
                                  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 33%">
                                      <span class="sr-only">33% Complete (danger)</span>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <div class="task-info">
                                  <div class="desc">Lote 3 - Santa Laura de Vucina</div>
                                  <div class="percent">45%</div>
                              </div>
                              <div class="progress progress-striped active">
                                  <div class="progress-bar"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                                      <span class="sr-only">45% Complete</span>
                                  </div>
                              </div>

                          </a>
                      </li>
                      <li class="external">
                          <a href="#">Ver todos os lotes em andamento</a>
                      </li>
                  </ul>
              </li>
              <!-- settings end -->
              <!-- inbox dropdown start-->
              <li id="header_inbox_bar" class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                      <i class="fa fa-envelope-o"></i>
                      <span class="badge bg-important">5</span>
                  </a>
                  <ul class="dropdown-menu extended inbox">
                      <div class="notify-arrow notify-arrow-red"></div>
                      <li>
                          <p class="red">Você tem 5 novas notificações</p>
                      </li>
                      <li>
                          <a href="#">
                              <span class="photo"><img alt="avatar" src="<?php echo $layoutAsset; ?>/img/avatar-mini.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Ademir Neves Ferreira</span>
                                    <span class="time">Agora</span>
                                    </span>
                                    <span class="message">
                                        Registro de atividade D0
                                    </span>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <span class="photo"><img alt="avatar" src="<?php echo $layoutAsset; ?>/img/avatar-mini2.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Diego Wendell</span>
                                    <span class="time">10 mins</span>
                                    </span>
                                    <span class="message">
                                     Lançados diagnósticos de gestação
                                    </span>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <span class="photo"><img alt="avatar" src="<?php echo $layoutAsset; ?>/img/avatar-mini3.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Hernani Ceolin</span>
                                    <span class="time">3 hrs</span>
                                    </span>
                                    <span class="message">
                                        Novo lote cadastrado
                                    </span>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <span class="photo"><img alt="avatar" src="<?php echo $layoutAsset; ?>/img/avatar-mini4.jpg"></span>
                                    <span class="subject">
                                    <span class="from">Altair</span>
                                    <span class="time">2 dias</span>
                                    </span>
                                    <span class="message">
                                        Registro de atividade D7
                                    </span>
                          </a>
                      </li>
                      <li>
                          <a href="#">Ver todas notificações</a>
                      </li>
                  </ul>
              </li>
              <!-- inbox dropdown end -->
              <!-- notification dropdown start-->
              <li id="header_notification_bar" class="dropdown">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                      <i class="fa fa-bell-o"></i>
                      <span class="badge bg-warning">7</span>
                  </a>
                  <ul class="dropdown-menu extended notification">
                      <div class="notify-arrow notify-arrow-yellow"></div>
                      <li>
                          <p class="yellow">7 atividades em aberto</p>
                      </li>
                      <li>
                          <a href="#">
                              <span class="label label-danger"><i class="fa fa-bolt"></i></span>
                              D7 - Fazenda Esperança
                              <span class="small italic">Hoje</span>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <span class="label label-warning"><i class="fa fa-bell"></i></span>
                              D9 - Fazenda Esperança
                              <span class="small italic">Amanhã</span>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <span class="label label-danger"><i class="fa fa-bolt"></i></span>
                              DG - Fazenda Buriti
                              <span class="small italic"><?php echo date('d-m', (time()+(86400*3))); ?></span>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <span class="label label-success"><i class="fa fa-plus-circle"></i></span>
                              IATF - Fazenda Ouro Verde
                              <span class="small italic"><?php echo date('d-m', (time()+(86400*5))); ?></span>
                          </a>
                      </li>
                      <li>
                          <a href="#">
                              <span class="label label-info"><i class="fa fa-bullhorn"></i></span>
                              Application error.
                              <span class="small italic">10 mins</span>
                          </a>
                      </li>
                      <li>
                          <a href="#">Ver todas atividades</a>
                      </li>
                  </ul>
              </li>
              <!-- notification dropdown end -->
          </ul>
          </div>
          <div class="top-nav ">
              <ul class="nav pull-right top-menu">
                  <li>
                      <input type="text" class="form-control search" placeholder="Buscar">
                  </li>
                  <!-- user login dropdown start-->
                  <li class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <img alt="" src="<?php echo $layoutAsset; ?>img/avatar2_small.jpg">
                          <span class="username">Moisés Máximo</span>
                          <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu extended logout">
                          <div class="log-arrow-up"></div>
                          <li><a href="#"><i class=" fa fa-briefcase"></i>Perfil</a></li>
                          <li><a href="#"><i class="fa fa-cog"></i> Ajustes</a></li>
                          <li><a href="#"><i class="fa fa-bell"></i> Avisos</a></li>
                          <li><a href="<?PHP echo $url ?>sair"><i class="fa fa-sign-out"></i> Sair do sistema</a></li>
                      </ul>
                  </li>
                  <!-- user login dropdown end -->
              </ul>
          </div>
      </header>
      <!--header end-->
	<?php } ?>
