
<div class="loading-modal no-print"><a class="modal-spin fa white fa-spinner fa-spin fa-4x fa-fw"></a></div>
<div class="dark-screen no-print"></div>
<div class="history-main-content"></div>


<!-- =========================
     SCRIPTS
============================== -->

<script>
/* =================================
   LOADER
=================================== */
// makes sure the whole site is loaded
jQuery(window).load(function() {
    "use strict";
        // will first fade out the loading animation
    jQuery(".status").fadeOut();
        // will fade out the whole DIV that covers the website.
    jQuery(".preloader").delay(1000).fadeOut("slow");
})

</script>

<script src="<?php echo $layoutAsset; ?>js/bootstrap.min.js"></script>
<script src="<?php echo $layoutAsset; ?>js/retina-1.1.0.min.js"></script>
<script src="<?php echo $layoutAsset; ?>js/smoothscroll.js"></script>
<script src="<?php echo $layoutAsset; ?>js/jquery.scrollTo.min.js"></script>
<script src="<?php echo $layoutAsset; ?>js/jquery.localScroll.min.js"></script>
<script src="<?php echo $layoutAsset; ?>js/owl.carousel.min.js"></script>
<script src="<?php echo $layoutAsset; ?>js/nivo-lightbox.min.js"></script>
<script src="<?php echo $layoutAsset; ?>js/simple-expand.min.js"></script>
<script src="<?php echo $layoutAsset; ?>js/jquery.nav.js"></script>
<script src="<?php echo $layoutAsset; ?>js/jquery.fitvids.js"></script>
<script src="<?php echo $layoutAsset; ?>js/jquery.ajaxchimp.min.js"></script>
<script src="<?php echo $layoutAsset; ?>js/jquery.maskedinput.js"></script>
<script src="<?php echo $layoutAsset; ?>js/custom.js"></script>
<script src="<?php echo $appAsset; ?>js/slidebars.min.js"></script>
<script src="<?php echo $appAsset; ?>js/jquery.nicescroll.js"></script>
<script class="include" type="text/javascript" src="<?php echo $layoutAsset; ?>js/jquery.dcjqaccordion.2.7.js"></script>
<script src="<?php echo $layoutAsset; ?>js/jquery.scrollTo.min.js"></script>
<script src="<?php echo $appAsset; ?>js/landX4.js"></script>
<script src="<?php echo $cupcakeAsset; ?>js/cupcake.js?v=20160908"></script>
<!-- ****************
      After neccessary customization/modification,
      Please minify JavaScript/jQuery according to
      http://browserdiet.com/en/ for better performance
     **************** -->

    <?php if ($alert !== false) { ?>
    <script>
    $(document).ready(function() {
        CupcakeAlert('<?php echo $alert; ?>');
    });
    </script>
    <?php } ?>

    <?php if ($topFull !== false) { ?>
        <button class="noty" style="display: none;" id="top-full-call" data-noty-options='{<?php echo $topFull; ?>}'></button>
        <script>
        $(document).ready(function() {
            $('#top-full-call').click();
        });
        </script>
    <?php } ?>

    <?php if ($modal !== false) { ?>
        <div class="modal hide fade" id="cupcakeModal">
            <?php echo $modal; ?>
        </div>

        <script>
        $(document).ready(function() {
            $('#cupcakeModal').modal('show');
        });
        </script>
    <?php } ?>

</body>
</html>