<!DOCTYPE HTML>
<html lang="pt-br">
<head>

	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<title><?php echo $titulo; ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta NAME="Author" CONTENT="Gê Bender">
	<meta name="description" content="<?php echo $description?>">

	<?php foreach ($extraHeaderA as $header) {
	    echo $header;
	} ?>

<!-- BOOTSTRAP -->
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/bootstrap.min.css">

<!-- FONT ICONS -->
<!-- IonIcons
<link rel="stylesheet" href="assets/ionicons/css/ionicons.css">
-->

<!-- Font Awesome -->
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/font-awesome/css/font-awesome.min.css">

<!-- Elegant Icons
<link rel="stylesheet" href="assets/elegant-icons/style.css"> -->
<!--[if lte IE 7]><script src="assets/elegant-icons/lte-ie7.js"></script><![endif]-->

<!-- CAROUSEL AND LIGHTBOX -->
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/owl.theme.css">
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/owl.carousel.css">
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/nivo-lightbox.css">
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/nivo_themes/default/default.css">

<!-- COLORS -->
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/colors/blue.css">
<!-- <link rel="stylesheet" href="css/colors/red.css"> -->
<!-- <link rel="stylesheet" href="css/colors/green.css"> -->
<!-- <link rel="stylesheet" href="css/colors/purple.css"> -->
<!-- <link rel="stylesheet" href="css/colors/orange.css"> -->
<!-- <link rel="stylesheet" href="css/colors/blue-munsell.css"> -->
<!-- <link rel="stylesheet" href="css/colors/slate.css">
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/colors/yellow.css"> -->

<!-- CUSTOM STYLESHEETS -->
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/styles.css">
<link rel="stylesheet" href="<?php echo $appAsset; ?>css/landX4.css?v=20150701">

<!-- RESPONSIVE FIXES -->
<link rel="stylesheet" href="<?php echo $layoutAsset; ?>css/responsive.css">

<!--[if lt IE 9]>
			<script src="js/html5shiv.js"></script>
			<script src="js/respond.min.js"></script>
<![endif]-->

<!-- ****************
      After neccessary customization/modification, Please minify HTML/CSS according to http://browserdiet.com/en/ for better performance
     **************** -->


    <link type="text/css" rel='stylesheet' href="<?php echo $layoutAsset; ?>jquery-ui/jquery-ui.min.css">

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<?php foreach ($extraHeaderB as $header) {
	    echo $header;
	} ?>

	<link rel="shortcut icon" href="<?php echo $appAsset; ?>images/<?php echo $favicon; ?>">
    <link rel="icon" href="<?php echo $appAsset; ?>images/<?php echo $favicon; ?>" type="image/x-icon">
    <script type="text/javascript" src="<?php echo $layoutAsset; ?>js/jquery.min.js"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-65021268-1', 'auto');
      ga('send', 'pageview');

    </script>

</head>

<body>

<div class="preloader">
  <div class="status">&nbsp;</div>
</div>

