<?php
if ($v->getNoVisibleElements() === false) { ?>
	<!-- topbar starts -->
	<div class="navbar">
		<div class="navbar-inner fixed-nav">
			<div class="container-fluid">

				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="fa fa-bars"></span>
				</a>
				<a style="line-height: 1;" href="<?php echo $v->getIndexPainel(); ?>"> <i style="margin-bottom: 5px;" class="logo-top"></i> <span class="white brand-name"><?php echo $v->getNomeSistema(); ?></span></a>

				<!-- user dropdown starts -->
				<div class="btn-group pull-right" >
					<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="fa fa-user"></i><span class="hidden-phone"> <?php echo (isset($userNome) === true) ? $userNome : ''; ?></span>
						<span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
<!-- 						<li><a href="#"><i class="darkgray fa fa-pencil-square-o"></i> Editar perfil</a></li> -->
<!-- 						<li class="divider"></li> -->
						<li><a class="ajax-nav" href="<?php echo $index ?>sair"><i class="darkgray fa fa-power-off"></i> Sair do sistema</a></li>
					</ul>
				</div>
				<!-- user dropdown ends -->

				<div class="top-nav nav-collapse">
					<ul class="nav" style="max-width: 330px;margin: auto;float: none;">
						<li>
							<form method="get" class="pull-left" id="busca-topo" action="<?php echo $index; ?>busca/" style="margin-bottom: 10px;">
								<div style="margin-bottom: 0px;" class="input-append"><input focus="true" value="<?php echo @$_GET['chave']; ?>" id="chave-busca" name="chave" required="required" class="input-large" placeholder="Telefone, cpf, pedido, etc" style="margin-bottom: 0px;height: 30px;font-size: 16px;" type="text"><button style="margin: initial;margin-left: -1px; height: 40px;text-shadow: initial;" id="btn-busca-topo" class="add-on btn btn-primary"><i class="fa fa-2x fa-search"></i></button></div>
							</form>
						</li>
					</ul>
				</div>
				<!--/.nav-collapse -->
			</div>
		</div>
	</div>
	<!-- topbar ends -->
	<div style="display: block;overflow: hidden;height: 55px;"></div>
<?php } ?>
